export const courses = [
  {
    id: 1,
    title: 'Mobile App Development The Complete Guide',
    description: 'Learn UIKIT, JavaScript1 and web programming. HTML development | React and Deployment | Query',
    category: 'Mobile Development',
    image: '/mobileapp.png',
    instructor: 'Kathryn Murphy',
    instructorTitle: 'Senior Developer',
    instructorRating: 4.8,
    instructorStudents: 15400,
    instructorBio: 'With over 10 years of experience in mobile app development, Kathryn Murphy brings practical, industry-level expertise to every course.',
    price: 89.99,
    originalPrice: 248.00,
    rating: 4.3,
    reviews: 1200,
    students: 229,
    duration: 31,
    lessons: 17,
    resources: 40,
    learningPoints: [
      'Prepare for becoming a Professional Front-End Developer',
      'Syntax of Code Optimized to Connect and interact with web',
      'Understand and use real time UI Engaging with JavaScript',
      'CSS Class Designing with JavaScript',
      'Learn Database Configurations with JavaScript',
      'Complete Web Development with React',
    ],
    requirements: [
      'Have an internet connection (or at least working internet)',
      'It is highly recommended that you download the free Firebug text editor',
      'It is recommended that you download the free Firefox text editor',
    ],
    aboutDescription: 'This comprehensive guide covers everything you need to know about mobile app development. From basic concepts to advanced techniques, you\'ll learn how to build professional-grade applications. Explore different programming languages, frameworks, and best practices used by leading companies.',
    sections: [
      { title: 'Program Information 2023/2024 Edition', lessons: 3, hours: 2 },
      { title: 'About This Course', lessons: 1, hours: 0.5 },
      { title: 'Real-Oriented Structures', lessons: 3, hours: 1.5 },
      { title: 'HTML Foundations: Building The Foundation', lessons: 2, hours: 1 },
      { title: 'Certified HTMTL Foundations 2023/2024', lessons: 5, hours: 3 },
      { title: 'Your Development Toolbox', lessons: 3, hours: 2 },
      { title: 'JavaScript Specialist', lessons: 5, hours: 2.5 },
    ]
  },
 
  {
    id: 3,
    title: 'Java Swing (GUI) Programming From Beginner to Expert',
    description: 'Learn desktop application development with Java Swing',
    category: 'Java',
    image: '/java-swing-gui-programming-desktop.png',
    instructor: 'Bessie Cooper',
    instructorTitle: 'Java Developer',
    instructorRating: 4.6,
    instructorStudents: 10500,
    instructorBio: 'Expert Java developer with 8+ years of experience in building scalable applications.',
    price: 89.99,
    originalPrice: 199.99,
    rating: 4.5,
    reviews: 320,
    students: 229,
    duration: 20,
    lessons: 11,
    resources: 38,
    learningPoints: [
      'Java fundamentals and OOP concepts',
      'Swing components and layouts',
      'Event handling and listeners',
      'Building complete GUI applications',
      'Database integration',
      'Deployment strategies',
    ],
    requirements: [
      'Java development kit installed',
      'IDE like Eclipse or IntelliJ IDEA',
      'Basic programming knowledge',
    ],
    aboutDescription: 'Master Java Swing for desktop application development. This course provides hands-on training in creating professional GUI applications with Java.',
    sections: [
      { title: 'Java Fundamentals', lessons: 3, hours: 2 },
      { title: 'Swing Basics', lessons: 3, hours: 2 },
      { title: 'Advanced Components', lessons: 3, hours: 2.5 },
      { title: 'Real Applications', lessons: 4, hours: 3 },
    ]
  },
  {
    id: 4,
    title: 'Python for Data Science and Machine Learning Bootcamp',
    description: 'Comprehensive Python training for data science and ML',
    category: 'Python',
    image: '/python-data-science-machine-learning.png',
    instructor: 'Bessie Cooper',
    instructorTitle: 'Data Scientist',
    instructorRating: 4.9,
    instructorStudents: 18900,
    instructorBio: 'Data science expert with experience at leading tech companies.',
    price: 129.99,
    originalPrice: 249.99,
    rating: 4.8,
    reviews: 450,
    students: 350,
    duration: 40,
    lessons: 15,
    resources: 50,
    learningPoints: [
      'Python programming for data science',
      'NumPy and Pandas libraries',
      'Data visualization',
      'Machine learning algorithms',
      'Deep learning basics',
      'Real-world projects',
    ],
    requirements: [
      'Python 3 installed',
      'Jupyter Notebook',
      'Basic math knowledge',
    ],
    aboutDescription: 'This bootcamp covers everything needed to start a career in data science and machine learning using Python.',
    sections: [
      { title: 'Python Basics', lessons: 2, hours: 1.5 },
      { title: 'Data Analysis', lessons: 3, hours: 2 },
      { title: 'Machine Learning', lessons: 4, hours: 3 },
      { title: 'Projects', lessons: 6, hours: 4.5 },
    ]
  },
  {
    id: 5,
    title: 'Introduction to Digital Marketing',
    description: 'Learn digital marketing fundamentals and strategies',
    category: 'Digital Media',
    image: '/digital-marketing-strategy-online.png',
    instructor: 'Theresa Webb',
    instructorTitle: 'Marketing Expert',
    instructorRating: 4.7,
    instructorStudents: 9800,
    instructorBio: 'Digital marketing professional with 12+ years of experience.',
    price: 79.99,
    originalPrice: 179.99,
    rating: 4.6,
    reviews: 180,
    students: 198,
    duration: 18,
    lessons: 15,
    resources: 30,
    learningPoints: [
      'Digital marketing fundamentals',
      'SEO optimization',
      'Social media marketing',
      'Email marketing',
      'Content strategy',
      'Analytics and reporting',
    ],
    requirements: [
      'Basic internet knowledge',
      'Willingness to learn digital tools',
    ],
    aboutDescription: 'Master the essentials of digital marketing and propel your career in the fastest-growing industry.',
    sections: [
      { title: 'Marketing Fundamentals', lessons: 3, hours: 2 },
      { title: 'SEO & SEM', lessons: 3, hours: 2.5 },
      { title: 'Social Media', lessons: 3, hours: 2 },
      { title: 'Analytics', lessons: 3, hours: 1.5 },
      { title: 'Campaigns', lessons: 3, hours: 2 },
    ]
  },
  {
    id: 6,
    title: 'Advanced JavaScript Programming',
    description: 'Deep dive into JavaScript for web development',
    category: 'Web Development',
    image: '/javascript-programming-web-development.png',
    instructor: 'Bessie Cooper',
    instructorTitle: 'Full Stack Developer',
    instructorRating: 4.8,
    instructorStudents: 14200,
    instructorBio: 'Full stack developer specializing in JavaScript and modern web technologies.',
    price: 99.99,
    originalPrice: 229.99,
    rating: 4.7,
    reviews: 260,
    students: 300,
    duration: 28,
    lessons: 12,
    resources: 42,
    learningPoints: [
      'Advanced JavaScript concepts',
      'Asynchronous programming',
      'DOM manipulation',
      'Event handling',
      'ES6+ features',
      'Web APIs',
    ],
    requirements: [
      'Basic JavaScript knowledge',
      'Text editor',
      'Modern web browser',
    ],
    aboutDescription: 'Take your JavaScript skills to the next level with advanced concepts and best practices.',
    sections: [
      { title: 'Advanced Concepts', lessons: 3, hours: 2.5 },
      { title: 'Async Programming', lessons: 3, hours: 2 },
      { title: 'DOM & Events', lessons: 2, hours: 1.5 },
      { title: 'ES6+ Features', lessons: 2, hours: 1.5 },
      { title: 'Projects', lessons: 2, hours: 2 },
    ]
  },
 
  {
    id: 9,
    title: 'The Complete Cyber Security Course Hackers Exposed!',
    description: 'Comprehensive cybersecurity training course',
    category: 'Software Development',
    image: '/cybersecurity-hacking-protection.png',
    instructor: 'Cleaner Pena',
    instructorTitle: 'Security Expert',
    instructorRating: 4.8,
    instructorStudents: 15600,
    instructorBio: 'Cybersecurity professional with decades of experience.',
    price: 89.99,
    originalPrice: 219.99,
    rating: 4.2,
    reviews: 220,
    students: 360,
    duration: 32,
    lessons: 15,
    resources: 45,
    learningPoints: [
      'Security fundamentals',
      'Network security',
      'Cryptography',
      'Ethical hacking',
      'Penetration testing',
      'Incident response',
    ],
    requirements: [
      'Basic IT knowledge',
      'Linux terminal experience preferred',
    ],
    aboutDescription: 'Master cybersecurity and ethical hacking with practical, real-world scenarios.',
    sections: [
      { title: 'Security Basics', lessons: 3, hours: 2 },
      { title: 'Network Security', lessons: 3, hours: 2.5 },
      { title: 'Ethical Hacking', lessons: 4, hours: 3 },
      { title: 'Advanced Topics', lessons: 5, hours: 3.5 },
    ]
  },
  {
    id: 10,
    title: 'Blockchain and Cryptocurrency Explained',
    description: 'Understand blockchain technology and cryptocurrencies',
    category: 'Software Development',
    image: '/blockchain-cryptocurrency-bitcoin.png',
    instructor: 'Bessie Cooper',
    instructorTitle: 'Blockchain Developer',
    instructorRating: 4.6,
    instructorStudents: 9200,
    instructorBio: 'Blockchain specialist with expertise in crypto technologies.',
    price: 99.99,
    originalPrice: 229.99,
    rating: 4.5,
    reviews: 150,
    students: 250,
    duration: 24,
    lessons: 13,
    resources: 35,
    learningPoints: [
      'Blockchain fundamentals',
      'Bitcoin and altcoins',
      'Smart contracts',
      'DeFi basics',
      'Wallet security',
      'Trading basics',
    ],
    requirements: [
      'Basic tech knowledge',
      'Interest in cryptocurrency',
    ],
    aboutDescription: 'Complete guide to understanding blockchain technology and the cryptocurrency revolution.',
    sections: [
      { title: 'Blockchain Basics', lessons: 3, hours: 2 },
      { title: 'Cryptocurrencies', lessons: 3, hours: 2 },
      { title: 'Smart Contracts', lessons: 3, hours: 2.5 },
      { title: 'Applications', lessons: 4, hours: 2.5 },
    ]
  },
  {
    id: 11,
    title: 'React.js Mastery: Build Modern Web Applications',
    description: 'Advanced React.js training for web developers',
    category: 'Web Development',
    image: '/react-javascript-web-applications.png',
    instructor: 'Bessie Cooper',
    instructorTitle: 'React Expert',
    instructorRating: 4.9,
    instructorStudents: 16700,
    instructorBio: 'React specialist working with leading tech companies.',
    price: 119.99,
    originalPrice: 249.99,
    rating: 4.8,
    reviews: 380,
    students: 420,
    duration: 38,
    lessons: 16,
    resources: 52,
    learningPoints: [
      'React hooks and state',
      'Component composition',
      'Redux for state management',
      'React Router',
      'Performance optimization',
      'Testing strategies',
    ],
    requirements: [
      'JavaScript knowledge',
      'Node.js installed',
      'Text editor',
    ],
    aboutDescription: 'Master React.js and build scalable modern web applications with industry best practices.',
    sections: [
      { title: 'React Fundamentals', lessons: 3, hours: 2 },
      { title: 'Hooks and State', lessons: 3, hours: 2.5 },
      { title: 'Advanced Patterns', lessons: 3, hours: 2.5 },
      { title: 'Real Projects', lessons: 7, hours: 5 },
    ]
  },
  {
    id: 12,
    title: 'Node.js and Express.js Complete Guide',
    description: 'Full-stack JavaScript development with Node.js',
    category: 'Web Development',
    image: '/nodejs-express-backend-development.png',
    instructor: 'Bessie Cooper',
    instructorTitle: 'Backend Developer',
    instructorRating: 4.7,
    instructorStudents: 12400,
    instructorBio: 'Backend developer specializing in Node.js and JavaScript ecosystems.',
    price: 109.99,
    originalPrice: 239.99,
    rating: 4.6,
    reviews: 210,
    students: 290,
    duration: 30,
    lessons: 14,
    resources: 40,
    learningPoints: [
      'Node.js fundamentals',
      'Express.js framework',
      'REST APIs',
      'Database integration',
      'Authentication',
      'Deployment',
    ],
    requirements: [
      'JavaScript knowledge',
      'Node.js installed',
      'Database basics',
    ],
    aboutDescription: 'Complete training in backend development using Node.js and Express.js.',
    sections: [
      { title: 'Node.js Basics', lessons: 3, hours: 2 },
      { title: 'Express.js', lessons: 3, hours: 2.5 },
      { title: 'APIs & Databases', lessons: 3, hours: 2.5 },
      { title: 'Projects', lessons: 5, hours: 4 },
    ]
  }
];
